export default {
  PRIMARY_COLOR: '#39BFBA',
  PLACEHOLDER_COLOR: '#ffffffb0',
  HEADER_COLOR: '#2C908C',
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_WEIGHT_BOLD: '700',
  HEADER_HEIGHT: 60,
  CONTAINER_PADDING: 10,
  BORDER_COLOR: 'rgba(0,0,0,.1)'
};
