export default {
  PRIMARY_COLOR: '#39BFBA',
  HEADER_COLOR: '#2C908C',
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_WEIGHT_BOLD: '700',
  HEADER_HEIGHT: 55,
  CONTAINER_PADDING: 10,
};
